// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vazdvgbpujjlchqfwndz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhemR2Z2JwdWpqbGNocWZ3bmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1ODg2NDUsImV4cCI6MjA3MzE2NDY0NX0.v2NA_ZaFer4ZWB3JaemmB3BMS_LpjC0pjz3vEocmSnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // CRITICAL for password reset!
    flowType: 'pkce'
  }
});